### PR TITLE
Login

### PR DESCRIPTION
**Pull request by frozenjava**
## Description
Getting the RETS Version from the headers when logging in

## GitHub Issues
#60

### CODE REVIEW

**Comment by mcrowson** [comment]
A few things:
- Can we test this?
- Should we allow them to supply a rets_version in case the server doesn't return one or they want to override?

**Comment by frozenjava** [comment]
Can we test this?
Sure, I'll write a test for it.

Should we allow them to supply a rets_version in case the server doesn't return one or they want to override?
I was thinking about this but I couldn't think of a use case where you would intentionally want to use a wrong version so I didn't implement it.

**Comment by mcrowson** [comment]
I was thinking more of the case where the server didn't provide it.

**Comment by frozenjava** [comment]
If the server doesn't provide it then we use the version the use provided or the default (1.5)

**Comment by mcrowson** [comment]
That would work.

**Comment by frozenjava** [comment]
Thats how its working right now

**Pull request merged**
